---
# provision into aws classic cloud
- name: provision in aws
  hosts: localhost
  gather_facts: False
  vars:
    image: "ami-9a6ed3f2"
    keypair: "sdicu"
    instance_type: "m1.small"
    group: "sdicu"

  tasks:
    - name: provision into aws classic
      local_action: ec2 region=us-east-1 image={{ image }} keypair={{ keypair }} instance_type={{ instance_type }} group={{ group }} count=1 wait=yes instance_tags="Name=zabbix-test-server"
      register: ec2_info

    - debug: var=ec2_info

